name: 'CI Test Result in Slack'
description: 'Notify the test result from junitxml file to any slack channel'
branding:
  icon: 'bell'
  color: 'gray-dark'
inputs:
  title:
    description: 'Title of the test result which will appear in slack message'
    required: true
  slackbotid:
    description: 'ID of Slack bot configured'
    required: true
  slackbottoken:
    description: 'Token of Slack bot configured'
    required: true
  slackchannel:
    description: 'Channel name to post the message'
    required: true
  junitxml_filepath:
    description: 'Filepath of junitxml file from the root directory'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.title }}
    - ${{ inputs.slackbotid }}
    - ${{ inputs.slackbottoken }}
    - ${{ inputs.slackchannel }}
    - ${{ inputs.junitxml_filepath }}
